### ISSUE TITLE
Error: Unable to resolve action `szenius/set-timezone@v2`, unable to find version `v2`

### ISSUE THREAD

**Issue by bumb7ebee** [szenius/set-timezone#22]
The version should be changed to v2.0 instead of v2.

**Comment by JaLe29** [comment]
Looks like there is a an issue with example.

You muse use:
```
              - name: Set Timezone
                uses: szenius/set-timezone@v2.0
            
```
![image](https://github.com/szenius/set-timezone/assets/22296816/dc106602-b062-4e74-827f-5af0e1bff23c)

**Comment by bumb7ebee** [comment]
This [PR](https://github.com/szenius/set-timezone/pull/21) solves this problem.
