### ISSUE TITLE
Node 12 deprecation

### ISSUE THREAD

**Issue by gereons** [szenius/set-timezone#8]
I'm getting this warning/info from github: 

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: szenius/set-timezone

**Comment by TWiStErRob** [comment]
Came here to report the same, looks like it should be solved by https://github.com/szenius/set-timezone/pull/7, thanks @doregex!

**Comment by szenius** [comment]
Sorry for the wait. I've merged and released the new version 1.1. Will be updating the README later on. Thanks all!
